ARG PYTHON=python:3.12.7-alpine

# Building stage +++++++++++++++++++++++++++++++++++++++++
FROM ${PYTHON} AS builder

# Add build-time dependencies ----------------------------
RUN apk update

# Create venv --------------------------------------------
RUN python3 -m venv --upgrade-deps /venv
ENV PATH=/venv/bin:$PATH

# Install Python requirements ----------------------------
COPY ./requirements /requirements
RUN pip install -r /requirements/dev.requirements.txt

# Final stage ++++++++++++++++++++++++++++++++++++++++++++
FROM ${PYTHON}

# Add runtime dependencies -------------------------------
RUN apk update

# Copy Python environment --------------------------------
COPY --from=builder /venv/ /venv
ENV PATH=/venv/bin:$PATH

# Copy the app ------------------------------------------
COPY ./app /app
# Copy additional files required for linting
COPY ./typing /typing
COPY ./pyproject.toml /pyproject.toml

# Command steps:
# - Run isort, autoflake, black, and mypy
# - Run tests under the Coverage module
CMD sh -c "isort ./app ./typing; \
           autoflake ./app ./typing; \
           black ./app ./typing; \
           mypy && \
           coverage run ./app/manage.py test ${TEST_TARGET:-app} && \
           coverage html;"
