ARG PYTHON=python:3.11-alpine

# Building stage +++++++++++++++++++++++++++++++++++++++++
FROM ${PYTHON} AS builder

# Add build-time dependencies ----------------------------
RUN apk update

# Create venv --------------------------------------------
RUN python3 -m venv /venv
ENV PATH=/venv/bin:$PATH

# Install Python requirements ----------------------------
COPY ./requirements /requirements
RUN pip install -r /requirements/dev.requirements.txt

# Final stage ++++++++++++++++++++++++++++++++++++++++++++
FROM ${PYTHON}

# Add runtime dependencies -------------------------------
RUN apk update

# Copy Python environment --------------------------------
COPY --from=builder /venv/ /venv
ENV PATH=/venv/bin:$PATH

# Copy the app ------------------------------------------
COPY ./app /app
# Copy aditional files required for linting
COPY ./stubs /stubs
COPY ./pyproject.toml /pyproject.toml

# Command steps:
# - Run isort, autoflake, black and mypy
# - Run tests under the Coverage module
# - Delete Coverage middlesteps and copy the files out
CMD sh -c "isort ./app; \
           autoflake ./app; \
           black ./app; \
           mypy; \
           cd ./app; \
           coverage run --source \".\" manage.py test && \
           coverage html; \
           cd ..; \
           rm -rf ./coverage/*; \
           rm -f ./app/.coverage; \
           [ -d ./app/htmlcov/ ] && mv ./app/htmlcov/* ./app/htmlcov/.[!.]* ./coverage; \
           rm -rf ./app/htmlcov"
