name: "${PROJECT_NAME:-boilerplate}-backend"

services:

  db:
    extends:
      file: ../common-services.yml
      service: db
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file: .env

  app:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    command: >
      sh -c "python manage.py setup
      && supervisord -c /etc/supervisor.d/supervisord.ini"
    volumes:
      - ./logs:/logs
      - ./media:/media
      - ./cert.pem:/etc/nginx/ssl/cert.pem
      - ./key.pem:/etc/nginx/ssl/key.pem
    ports:
      - "8000:8000"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    tty: true  # Provide color in the console
