import logging
from pathlib import Path
from random import shuffle
from typing import Any, overload
from unittest import TestCase
from unittest.mock import MagicMock, patch
from django.db import models
from django.test import RequestFactory, override_settings
from django.utils.timezone import now
from rest_framework import status
from rest_framework.generics import RetrieveAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
import extensions.utilities as utils
from extensions.models.mixins import CreatedAtMixin, UpdatedAtMixin
from extensions.utilities import env, uuid
from extensions.utilities.logging import LoggingConfigurationBuilder
from extensions.utilities.query_measurer import (
    QueryData,
    QueryMeasurerContext,
    StatementType,
    default_handler,
    query_measurer,
)
from extensions.utilities.test import AbstractModelTestCase, MockResponse, SampleFile, override_auto_now


class TestUtilities(TestCase):
    """Test the base utilities provided."""

    def test_Singleton(self) -> None:
        """Test the Singleton metaclass"""

        class TestClass(metaclass=utils.Singleton): ...

        self.assertEqual(id(TestClass()), id(TestClass()))

    def test_Undefined(self) -> None:
        """Test the _Undefined class."""
        with self.subTest("Test equality"):
            self.assertNotEqual(utils.Undefined, utils.Undefined)

        with self.subTest("Test bool"):
            self.assertFalse(utils.Undefined)

    def test_clear_Undefined(self) -> None:
        """Test the `clear_Undefined` function."""
        self.assertEqual(
            {"_key1": "_value1", "_key2": None},
            utils.clear_Undefined(_key1="_value1", _key2=None, _key3=utils.Undefined),
        )

    def test_ext(self) -> None:
        """Test the `ext` function."""
        cases = [
            ("_path/_to/_file/_filename._ext", "_ext"),
            ("_path/_file._with._multiple._exts", "_with._multiple._exts"),
            ("_path/_dot._in._the/middle._with_ext", "_with_ext"),
        ]
        for case, expected in cases:
            with self.subTest("Testing the extensions", case=case, ext=expected):
                self.assertEqual(expected, utils.ext(case))
                self.assertEqual(f".{expected}", utils.ext(case, leading_dot=True))
        # Edge case
        self.assertEqual("", utils.ext("filename_with_no_ext", leading_dot=True))

    def test_order_list(self) -> None:
        """Test the `order_list` function."""
        with self.subTest("Test regular sorting"):
            original_list = [5, 3, 1, 4]
            ordering_list = [str(n) for n in original_list]
            shuffle(ordering_list)
            result = utils.order_list(original_list, ordering_list)
            self.assertEqual([int(n) for n in ordering_list], result)
        with self.subTest("Missing value is appended"):
            original_list = [5, 3, 1, 4]
            ordering_list = [str(n) for n in original_list[:-2]]
            shuffle(ordering_list)
            result = utils.order_list(original_list, ordering_list)
            self.assertEqual([int(n) for n in ordering_list] + original_list[2:], result)
        with self.subTest("Test with mapping"):
            mapped_original_list_values = [5, 3, 1, 4]
            mapped_original_list = [{"item": n} for n in mapped_original_list_values]
            mapped_ordering_list = [str(n) for n in mapped_original_list_values]
            shuffle(mapped_ordering_list)
            mapped_result = utils.order_list(mapped_original_list, mapped_ordering_list, lambda x: str(x["item"]))
            self.assertEqual([{"item": int(n)} for n in mapped_ordering_list], mapped_result)


class TestTestUtilities(AbstractModelTestCase):
    """Test the test utilities provided."""

    class AutoNowConcreteModel(CreatedAtMixin, UpdatedAtMixin):
        class Meta:
            # Because extensions is not an "installed_app"
            app_label = uuid()

    MODELS = (AutoNowConcreteModel,)

    def test_override_auto_now(self) -> None:
        """Test the override_auto_now context manager."""
        with self.subTest("Test autogenerated value"):
            with override_auto_now() as new_time_value:
                obj = self.AutoNowConcreteModel._default_manager.create()
                self.assertEqual(new_time_value, obj.created_at)
                self.assertEqual(new_time_value, obj.updated_at)
            # Outside of context
            outside_obj = self.AutoNowConcreteModel._default_manager.create()
            self.assertNotEqual(new_time_value, outside_obj.created_at)
            self.assertNotEqual(new_time_value, outside_obj.updated_at)

        with self.subTest("Test given value"):
            given_value = now()
            with override_auto_now(given_value):
                obj = self.AutoNowConcreteModel._default_manager.create()
                self.assertEqual(given_value, obj.created_at)
                self.assertEqual(given_value, obj.updated_at)
            # Outside of context
            outside_obj = self.AutoNowConcreteModel._default_manager.create()
            self.assertNotEqual(given_value, outside_obj.created_at)
            self.assertNotEqual(given_value, outside_obj.updated_at)

    def test_MockResponse(self) -> None:
        """Test the MockResponse class."""
        with self.subTest("Test creating a MockResponse object"):
            code = 200
            json = {"_key": "_value"}
            obj = MockResponse(code, json)
            self.assertEqual(code, obj.status_code)
            self.assertEqual(json, obj.json())
            self.assertEqual(str(json), obj.text)
        with self.subTest("Test the `ok` property"):
            self.assertFalse(MockResponse(100).ok)
            self.assertTrue(MockResponse(200).ok)
            self.assertFalse(MockResponse(400).ok)

    def test_SampleFile(self) -> None:
        """Test the SampleFile class."""
        name = "_name"
        content = "_content"
        file = SampleFile(name=name, content=content)
        self.assertEqual(content.encode(), file.bytes)
        self.assertEqual(content, file.content)

    @patch("extensions.utilities.test.uuid")
    def test_SampleFile_default(self, uuid_mock: MagicMock) -> None:
        """Test creating a "default" SampleFile."""
        mock_uuid = "_uuid"
        uuid_mock.return_value = mock_uuid
        file = SampleFile()
        self.assertEqual(mock_uuid, file.name)
        self.assertEqual(b"", file.bytes)
        self.assertEqual("", file.content)

    def test_SampleFile_from_file_path(self) -> None:
        """Test the SampleFile `from_file_path` method."""

        @overload
        def normalize_line_endings(text: str) -> str: ...
        @overload
        def normalize_line_endings(text: bytes) -> bytes: ...
        def normalize_line_endings(text: str | bytes) -> str | bytes:
            """Make the line endings match regardless of OS."""
            if isinstance(text, bytes):
                return text.replace(b"\r", b"")
            return text.replace("\r", "")

        # Read the text file
        example_file_path = Path(__file__).parent / "example.txt"
        expected_name = example_file_path.name
        with open(example_file_path, "r") as example_file:
            expected_content = example_file.read()
        # Create and verify the sample file
        file = SampleFile.from_file_path(str(example_file_path))
        self.assertEqual(expected_name, file.name)
        self.assertEqual(normalize_line_endings(expected_content.encode()), normalize_line_endings(file.bytes))
        self.assertEqual(normalize_line_endings(expected_content), normalize_line_endings(file.content))


class TestEnvUtilities(TestCase):
    """Test the provided utilities to deal with environment variables."""

    def test__get_value(self) -> None:
        """Test the `_get_value` function."""
        key = "_key"
        value = "_value"
        with patch("extensions.utilities.env.ENV", {key: value}):
            retval = env._get_value(key)
            self.assertEqual(value, retval)

    def test__get_value_missing_key(self) -> None:
        """Test the `_get_value` function with a missing key."""
        key = "_key"
        with patch("extensions.utilities.env.ENV", {}):
            with self.assertRaises(KeyError):
                env._get_value(key)

    def test__get_value_missing_key_default(self) -> None:
        """Test the `_get_value` function with a missing key, when a default is provided."""
        key = "_key"
        default = "_value"
        with patch("extensions.utilities.env.ENV", {}):
            retval = env._get_value(key, default)
            self.assertEqual(default, retval)

    def test__get_value_empty_value_default(self) -> None:
        """Test the `_get_value` function with a key with an empty value, when a default is provided."""
        key = "_key"
        default = "_value"
        with patch("extensions.utilities.env.ENV", {key: ""}):
            retval = env._get_value(key, default)
            self.assertEqual(default, retval)

    def test_as_string(self) -> None:
        """Test the `as_string` function."""
        key = "_key"
        value = "_value"
        with patch("extensions.utilities.env.ENV", {key: value}):
            retval = env.as_string(key)
            self.assertIsInstance(retval, str)
            self.assertEqual(value, retval)

    def test_as_int(self) -> None:
        """Test the `as_int` function."""
        key = "_key"
        value = 1
        with patch("extensions.utilities.env.ENV", {key: str(value)}):
            retval = env.as_int(key)
            self.assertIsInstance(retval, int)
            self.assertEqual(value, retval)

    def test_as_list(self) -> None:
        """Test the `as_list` function."""
        key = "_key"
        value = ["_first", "_second", "_third"]
        with patch("extensions.utilities.env.ENV", {key: ",".join(value)}):
            retval = env.as_list(key)
            self.assertIsInstance(retval, list)
            self.assertEqual(value, retval)

    def test_as_list_missing_key_default(self) -> None:
        """Test the `as_list` function with a missing key, when a default is provided."""
        key = "_key"
        default = ["_first", "_second", "_third"]
        with patch("extensions.utilities.env.ENV", {}):
            retval = env.as_list(key, default)
            self.assertEqual(default, retval)

    def test_as_bool(self) -> None:
        """Test the `as_bool` function."""
        key = "_key"
        true_values = ["TRUE", "true", "tRuE", "1", "T", "t"]
        false_values = ["FALSE", "false", "fAlSe", "f", "F", "0"]
        # Test for true values
        for value in true_values:
            with (
                self.subTest("True values", value=value),
                patch("extensions.utilities.env.ENV", {key: str(value)}),
            ):
                retval = env.as_bool(key)
                self.assertIsInstance(retval, bool)
                self.assertEqual(True, retval)
        for value in false_values:
            with (
                self.subTest("False values", value=value),
                patch("extensions.utilities.env.ENV", {key: str(value)}),
            ):
                retval = env.as_bool(key)
                self.assertIsInstance(retval, bool)
                self.assertEqual(False, retval)

    def test_as_bool_missing_key_default(self) -> None:
        """Test the `as_bool` function with a missing key, when a default is provided."""
        key = "_key"
        default = True
        with patch("extensions.utilities.env.ENV", {}):
            retval = env.as_bool(key, default)
            self.assertEqual(default, retval)


class TestLoggingBuilder(TestCase):
    """Test the logging builder provided."""

    def test_add_formatter(self) -> None:
        """Test the `add_formatter` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        format = "_format"
        style = "_style"
        kwarg = "_kwarg"
        retval = builder.add_formatter(name, format, style, kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual({"format": format, "style": style, "kwarg": kwarg}, built["formatters"][name])

    def test_set_default_formatter(self) -> None:
        """Test the `set_default_formatter` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        builder.add_formatter(name, "_format", "_style")
        retval = builder.set_default_formatter(name)
        self.assertEqual(retval, builder)  # Builder returned itself
        self.assertEqual(name, builder._default_formatter)
        # Attempt to add a handler
        handler_name = "_handler_name"
        builder.add_handler(handler_name)
        built = builder.build()
        self.assertEqual(name, built["handlers"][handler_name]["formatter"])

    def test_set_default_formatter_overridden(self) -> None:
        """Test the default formatter can be overridden by passing the formatter when adding the handler."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        builder.add_formatter(name, "_format", "_style")
        builder.set_default_formatter(name)
        # Attempt to add a handler
        handler_name = "_handler_name"
        formatter_name = "_formatter_name"
        builder.add_handler(handler_name, formatter=formatter_name)
        built = builder.build()
        self.assertEqual(formatter_name, built["handlers"][handler_name]["formatter"])

    def test_set_default_formatter_missing_fails(self) -> None:
        """Test the `set_default_formatter` method fails if the formatter name passed does not exist."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        with self.assertRaises(ValueError) as ctx:
            builder.set_default_formatter(name)
        self.assertEqual(f"No formatter named {name} added.", str(ctx.exception))
        self.assertIsNone(builder._default_formatter)

    def test_add_filter(self) -> None:
        """Test the `add_filter` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        filter = "_filter"
        kwarg = "_kwarg"
        retval = builder.add_filter(name, filter, kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual({"()": filter, "kwarg": kwarg}, built["filters"][name])

    def test_add_handler(self) -> None:
        """Test the `add_handler` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        kwarg = "_kwarg"
        retval = builder.add_handler(name, kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual({"kwarg": kwarg}, built["handlers"][name])

    def test_add_console_handler(self) -> None:
        """Test the `add_console_handler` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        kwarg = "_kwarg"
        retval = builder.add_console_handler(name, kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual({"class": "logging.StreamHandler", "kwarg": kwarg}, built["handlers"][name])

    @patch("pathlib.Path.mkdir")
    def test_add_file_handler(self, mkdir_mock: MagicMock) -> None:
        """Test the `add_file_handler` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        file_path = utils.uuid()
        kwarg = "_kwarg"
        retval = builder.add_file_handler(name, file_path, kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual(
            {"class": "logging.FileHandler", "filename": file_path, "kwarg": kwarg}, built["handlers"][name]
        )
        # Make sure the mock was called correctly
        mkdir_mock.assert_called_once_with(parents=True, exist_ok=True)

    def test_add_logger(self) -> None:
        """Test the `add_logger` method."""
        builder = LoggingConfigurationBuilder()
        name = "_name"
        handlers = ["_handler1", "_handler2"]
        kwarg = "_kwarg"
        retval = builder.add_logger(name, handlers, kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual({"handlers": handlers, "kwarg": kwarg}, built["loggers"][name])

    def test_modify_root_logger(self) -> None:
        """Test the `modify_root_logger` method."""
        builder = LoggingConfigurationBuilder()
        kwarg = "_kwarg"
        retval = builder.modify_root_logger(kwarg=kwarg)
        self.assertEqual(retval, builder)  # Builder returned itself
        built = builder.build()
        self.assertEqual(kwarg, built["root"]["kwarg"])

    def test_build(self) -> None:
        """Test building an "empty" logger."""
        disable_existing = True
        builder = LoggingConfigurationBuilder(disable_existing)
        built = builder.build()
        self.assertEqual(
            {
                "version": 1,
                "disable_existing_loggers": disable_existing,
                "formatters": {},
                "filters": {},
                "handlers": {},
                "root": {},
                "loggers": {},
            },
            built,
        )


class TestQueryMeasurerContext(TestCase):
    """Test the QueryMeasurerContext class."""

    def test_queries_property(self) -> None:
        """Test the `queries` property."""
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", "SELECT", 1) for _ in range(5)]
        self.assertListEqual(ctx._queries, ctx.queries)

    def test_query_count_property(self) -> None:
        """Test the `query_count` property."""
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", "SELECT", 1) for _ in range(5)]
        self.assertEqual(len(ctx._queries), ctx.query_count)

    def test_query_time_property(self) -> None:
        """Test the `query_time` property."""
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", "SELECT", 1) for _ in range(5)]
        self.assertEqual(sum(q.time_ms for q in ctx._queries), ctx.query_time)

    def test_slowest_query_property(self) -> None:
        """Test the `slowest_query` property."""
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", "SELECT", value) for value in [5, 2, 4, 6, 2]]
        self.assertEqual(max(ctx.queries, key=lambda x: x.time_ms), ctx.slowest_query)

    def test_slowest_query_property_no_queries(self) -> None:
        """Test the `slowest_query` property raises a ValueError when there are no queries."""
        ctx = QueryMeasurerContext()
        with self.assertRaises(ValueError) as exc_ctx:
            ctx.slowest_query  # noqa: B018
        self.assertEqual("No queries present!", str(exc_ctx.exception))

    def test_get_filtered_queries(self) -> None:
        """Test the `get_filtered_queries` method."""
        statements: tuple[StatementType, ...] = ("SELECT", "UPDATE", "DELETE", "INSERT")
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", statement, 1) for _ in range(5) for statement in statements]
        for statement in statements:
            self.assertListEqual(
                [q for q in ctx._queries if q.statement == statement],
                ctx.get_filtered_queries(statement),
            )

    def test_get_filtered_queries_count(self) -> None:
        """Test the `get_filtered_queries_count` method."""
        statements: tuple[StatementType, ...] = ("SELECT", "UPDATE", "DELETE", "INSERT")
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", statement, 1) for _ in range(5) for statement in statements]
        for statement in statements:
            self.assertEqual(
                len([q for q in ctx._queries if q.statement == statement]),
                ctx.get_filtered_queries_count(statement),
            )

    def test_get_filtered_queries_time(self) -> None:
        """Test the `get_filtered_queries_time` method."""
        statements: tuple[StatementType, ...] = ("SELECT", "UPDATE", "DELETE", "INSERT")
        ctx = QueryMeasurerContext()
        ctx._queries = [QueryData("_sql", statement, 1) for _ in range(5) for statement in statements]
        for statement in statements:
            self.assertEqual(
                sum(q.time_ms for q in ctx._queries if q.statement == statement),
                ctx.get_filtered_queries_time(statement),
            )


class TestQueryMeasurer(AbstractModelTestCase):
    """Test the `query_measurer` decorator / context manager."""

    class TestModel(models.Model):
        """Model to test database queries"""

        field = models.IntegerField(default=1)

        class Meta:
            # Because extensions is not an "installed_app"
            app_label = uuid()

    MODELS = (TestModel,)

    def test_function_decorator(self) -> None:
        """
        Test using the `query_measurer` as a decorator for a function.

        This also tests that calling the function twice does not save the queries from previous calls.
        """

        def context_assert(ctx: QueryMeasurerContext) -> None:
            self.assertEqual(1, ctx.query_count)

        @query_measurer(handler=context_assert)
        def wrapped_function() -> None:
            # Make a query
            self.TestModel._default_manager.create()

        # Call the function to trigger the measure
        wrapped_function()

        # Call again to make sure that it's measured from the start
        wrapped_function()

    def test_view_decorator(self) -> None:
        """
        Test using the `query_measurer` as a decorator for a View class.

        This also tests that calling the View twice does not save the queries from previous calls.
        """

        def context_assert(ctx: QueryMeasurerContext) -> None:
            self.assertEqual(1, ctx.query_count)

        @query_measurer(handler=context_assert)
        class TestView(RetrieveAPIView):
            permission_classes = (AllowAny,)

            def retrieve(_self, *args: Any, **kwargs: Any) -> Response:
                # Make a query
                self.TestModel._default_manager.create()
                return Response(status=status.HTTP_200_OK)

        # Call the view to trigger the measure
        request_factory = RequestFactory()
        request = request_factory.get("")
        response = TestView.as_view()(request)
        self.assertEqual(status.HTTP_200_OK, response.status_code)

        # Call again to make sure that it's measured from the start
        response = TestView.as_view()(request)
        self.assertEqual(status.HTTP_200_OK, response.status_code)

    def test_class_decorator(self) -> None:
        """Test using the `query_measurer` on a non-View class fails."""

        with self.assertRaises(ValueError) as ctx:

            @query_measurer
            class BadClass(object): ...

        self.assertEqual("Query measurer can only wrap classes that are Views!", str(ctx.exception))

    def test_context_manager(self) -> None:
        """Test using the `query_measurer` as a context manager."""

        with query_measurer() as ctx:
            # Starts with no queries
            self.assertEqual(0, ctx.query_count)
            # Make an INSERT query
            self.TestModel._default_manager.create()
            self.assertEqual(1, ctx.query_count)

    def test_all_statements(self) -> None:
        """Test checking all different type of statements with `query_measurer`."""

        with query_measurer() as ctx:
            # Make an INSERT query
            self.TestModel._default_manager.create()
            # Make a SELECT query
            created = self.TestModel._default_manager.last()
            assert created is not None
            # Make a UPDATE query
            created.field = 2
            created.save()
            # Make a DELETE query
            created.delete()

        self.assertEqual(4, ctx.query_count)
        self.assertEqual(1, ctx.get_filtered_queries_count("INSERT"))
        self.assertEqual(1, ctx.get_filtered_queries_count("SELECT"))
        self.assertEqual(1, ctx.get_filtered_queries_count("UPDATE"))
        self.assertEqual(1, ctx.get_filtered_queries_count("DELETE"))

    @override_settings(DEBUG=False)
    def test_production_warning(self) -> None:
        """Test that using the measurer in production produces an error."""
        with self.assertLogs(level=logging.WARNING) as log_ctx:
            with query_measurer():
                ...
        self.assertIn(
            "WARNING:root:Warning! Query measurer should not be used in production; it's merely a debug tool.",
            log_ctx.output,
        )

    def test_default_handler(self) -> None:
        """Test the default handler."""

        with query_measurer() as ctx:
            # Make an INSERT query
            self.TestModel._default_manager.create()
            # Make a SELECT query
            created = self.TestModel._default_manager.last()
            assert created is not None
            # Make a UPDATE query
            created.field = 2
            created.save()
            # Make a DELETE query
            created.delete()

        with self.assertLogs(level=logging.DEBUG) as log_ctx:
            default_handler(ctx)

        self.assertIn(
            f"DEBUG:root:\nQuery Measurer results\n---\nTotal Queries: {ctx.query_count}\nTotal Time (ms): {ctx.query_time:.2f}\nSlowest Query: {f'{ctx.slowest_query.time_ms:.2f}'.rjust(6)} | {ctx.slowest_query.statement} | {ctx.slowest_query.raw_sql}\n---\n{'\n'.join([f'{f"{q.time_ms:.2f}".rjust(6)} | {q.statement} | {q.raw_sql}' for q in ctx.queries])}",
            log_ctx.output,
        )
