name: lint-and-test

on:
  push:
    branches: [ "main", "devops" ] # On devops to test changes to the action.
  pull_request:
    branches: [ "main" ]


# NOTE: these values are for testing only and not be used for production
env:
  SECRET_KEY: 'secret'
  DEBUG: ~
  ALLOWED_HOSTS: ~
  HTTPS_ENABLED: ~
  CORS_ALLOW_ALL_ORIGINS: ~
  CORS_ALLOWED_ORIGINS: ~
  ADMIN_EMAIL: ~
  ADMIN_PASSWORD: ~
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

jobs:
  run:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    services:
      db:
        image: postgres:15-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    steps:
    - uses: actions/checkout@v3.3.0

    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.requirements.txt

    - name: Run isort
      run: |
        isort --check-only ./app

    - name: Run autopep8
      id: autopep8
      run: |
        autopep8 --exit-code ./app
    - name: Fail if autopep8 made changes
      if: steps.autopep8.outputs.exit-code == 2
      run: exit 1

    - name: Run mypy
      run: |
        mypy


    - name: Run tests
      run: |
        cd ./app && python manage.py test
