name: run-tests

on:
  push:
    branches:
      - "main"
      - "devops"  # On devops to test changes to the action.
  pull_request:
    branches:
      - "main"

env:
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
  HTTPS_ENABLED: ${{ vars.HTTPS_ENABLED }}
  CORS_ALLOW_ALL_ORIGINS: ${{ vars.CORS_ALLOW_ALL_ORIGINS }}
  CORS_ALLOWED_ORIGINS: ${{ vars.CORS_ALLOWED_ORIGINS }}
  ADMIN_EMAIL: ${{ vars.ADMIN_EMAIL }}
  ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD}}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}

jobs:
  run-tests:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    services:
      db:
        image: postgres:15-alpine
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3.3.0

    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt

    - name: Run tests
      run: cd ./app && python manage.py test
